src/Entity/Article.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $support;

    /**
     * @ORM\Column(type="text")
     */
    private $contenu;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $auteur;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Theme", inversedBy="articles")
     */
    private $theme;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\MotCle", inversedBy="articles")
     */
    private $motCle;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reaction", mappedBy="article")
     */
    private $reactions;

    public function __construct()
    {
        $this->motCle = new ArrayCollection();
        $this->reactions = new ArrayCollection();
    }

    /**
     * @ORM\PrePersist
     * @ORM\PreUpdate
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getSupport(): ?string
    {
        return $this->support;
    }

    public function setSupport(string $support): self
    {
        $this->support = $support;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAuteur(): ?User
    {
        return $this->auteur;
    }

    public function setAuteur(?User $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getTheme(): ?Theme
    {
        return $this->theme;
    }

    public function setTheme(?Theme $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    /**
     * @return Collection|MotCle[]
     */
    public function getMotCle(): Collection
    {
        return $this->motCle;
    }

    public function addMotCle(MotCle $motCle): self
    {
        if (!$this->motCle->contains($motCle)) {
            $this->motCle[] = $motCle;
        }

        return $this;
    }

    public function removeMotCle(MotCle $motCle): self
    {
        if ($this->motCle->contains($motCle)) {
            $this->motCle->removeElement($motCle);
        }

        return $this;
    }

    /**
     * @return Collection|Reaction[]
     */
    public function getReactions(): Collection
    {
        return $this->reactions;
    }

    public function addReaction(Reaction $reaction): self
    {
        if (!$this->reactions->contains($reaction)) {
            $this->reactions[] = $reaction;
            $reaction->setArticle($this);
        }

        return $this;
    }

    public function removeReaction(Reaction $reaction): self
    {
        if ($this->reactions->contains($reaction)) {
            $this->reactions->removeElement($reaction);
            // set the owning side to null (unless already changed)
            if ($reaction->getArticle() === $this) {
                $reaction->setArticle(null);
            }
        }

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;


class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title')
           /* ->add('slug')*/
           /* ->add('created_at')*/
            ->add('ville')
            ->add('support', ChoiceType::class, array(
                'choices'=>array(
                    'Texte'=>'stock_texte',
                    'Video'=>'stock_video',
                    'Audio'=>'stock_audio'
                )
            ))
            ->add('contenu')
            ->add('image')
           /* ->add('auteur')*/
            ->add('theme', ChoiceType::class, array(
                'choices'=>array(
                    'Politique'=>'stock_politique',
                    'Economie'=>'stock_economie',
                    'Santé'=>'stock_sante',
                    'Design'=>'stock_design',
                    'Cuisine'=>'stock_cuisine'
                )
           ))
            ->add('motCle', UrlType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('article/index.html.twig', ['articles' => $articleRepository->findAll()]);
    }

    /**
     * @Route("/new", name="article_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('article_index');
        }

        return $this->render('article/new.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @param Article $article
     * @return Response
     * @Route("/{slug}", name="article_show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        return $this->render('article/show.html.twig', ['article' => $article]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Article $article): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('article_index', ['id' => $article->getId()]);
        }

        return $this->render('article/edit.html.twig', [
            'article' => $article,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Article $article): Response
    {
        if ($this->isCsrfTokenValid('delete'.$article->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('article_index');
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn">Delete</button>
</form>

templates/article/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{% block stysheets %} <link rel="stylesheet" href="{{ asset('assets/css/Crud.css') }}"> {% endblock %}

{% block body %}

<div class="container">
    <div class="card text-white mx-auto">
        <div class="card-body">

            {{ form_start(form) }}

                {{ form_row (form.title, {'attr': {'placeholder': "Titre de votre article"}}) }}
                {{ form_row (form.ville, {'attr': {'placeholder': "Ville consernée par votre aticle"}}) }}

                <div class="row">
                    <div class="col">
                        {{ form_row (form.theme, {'attr': {'placeholder': "Selectionnez le thême de votre article"}}) }}

                    </div>
                    <div class="col">
                        {{ form_row (form.support, {'attr': {'placeholder': "Selelctionnez le support de votre article"}}) }}
                    </div>
                </div>

                {{ form_row (form.contenu, {'attr': {'placeholder': "Votre article ici"}}) }}

                <div class="row">
                    <div class="col">
                        {{ form_row (form.image, {'attr': {'placeholder': "Ajoutez l'url de image de couverture à votre article"}}) }}

                    </div>
                    <div class="col">
                        {{ form_row (form.motCle, {'attr': {'placeholder': "Le  ou les mots-clés de votre article"}}) }}
                    </div>
                </div>

                <button class="btn btn-secondary col-3 m-md-5">{{ button_label|default('Save') }}</button>

            {{ form_end(form) }}

        </div>
    </div>
</div>

{% endblock %}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}

    <h1>Edit Article</h1>

    {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('article_index') }}">back to list</a>

    {{ include('article/_delete_form.html.twig') }}

{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
    <h1>Article index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Slug</th>
                <th>Created_at</th>
                <th>Ville</th>
                <th>Support</th>
                <th>Contenu</th>
                <th>Image</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.title }}</td>
                <td>{{ article.slug }}</td>
                <td>{{ article.createdAt ? article.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ article.ville }}</td>
                <td>{{ article.support }}</td>
                <td>{{ article.contenu }}</td>
                <td>{{ article.image }}</td>
                <td>
                    <a href="{{ path('article_show', {'slug': article.slug}) }}">show</a>
                    <a href="{{ path('article_edit', {'id': article.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('article_new') }}">Create new</a>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <h1>Créer un nouvel article</h1>

    {{ include('article/_form.html.twig') }}

    <a href="{{ path('article_index') }}">back to list</a>

{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ article.title }}{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" href="/assets/css/showArticle.css">
{% endblock %}

{% block body %}

    <div class="ad-title" style="background-image: url({{ article.image }})">
        <div class="container">
            <h1>{{ article.title }}</h1>
        </div>
    </div>

    <div class="container corpArticle">
        <div class="row">
            <div class="col-md-8 mb-3">
                {{ article.contenu | raw }}
                <a href="#">
                    <button type="button" class="btn btn-secondary">Débat</button>
                </a>
            </div>
            <div class="col-sm-12 col-md">
                {% set a = article.auteur %}
                <div class="row">
                    <div class="col-md-3">
                        <a href="#"><img class="avatar" src="{{ a.photo }}" alt="avatar de {{ a.nom }}{{ a.prenom }}"></a>
                    </div>
                    <div class="col">
                        <a href="{{ path("profile_journalist", {'slug': article.auteur.slug}) }}" style="color: white">
                            <h3>{{ a.prenom }} {{ a.nom }}</h3>
                        </a>
                        <span class="badge badge-primary">{{ a.articles|length }} articles</span>
                    </div>
                </div>
                {{ a.description|raw }}
            </div>
        </div>
    </div>

{% endblock %}